server:
  rootPath: /api/

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:test
  validationQuery: "/* MyService Health Check */ SELECT 1"

logging:
  level: INFO
  loggers:
    com.zuehlke.jso.camp2017: DEBUG
