#!groovy
pipeline {
    agent any
    stages {
        stage('Checkout') { // for display purposes
            steps{
                sh 'mkdir -f ./buildfolder'
                sh 'docker run -v buildfolder:/ switchback/git-debian https://github.com/mi-we/jso-camp-2017 master'
            }
        }
        stage('Build') { // for display purposes
            steps{
                sh 'docker pull openjdk:8-jdk'
            }
        }
    }
}